engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40
        ruby:
          mass_threshold: 23
  rubocop:
    enabled: true
ratings:
  paths:
    - '**.ru'
    - '**.rb'
    - '**.coffee'
    - '**.scss'
    - '**.js'
exclude_paths:
  - 'vendor/**/*'
  - 'config/initializers/**/*'
