language: ruby
cache: bundler
rvm: 2.3.0
before_script:
  - psql -c 'create database sitefull_deploy_test;' -U postgres
  - bundle exec rake db:test:prepare
bundler_args: --without production --path vendor/gems
addons:
  postgresql: '9.4'
  code_climate:
    repo_token: '3d0efcf309a76d2e9ce070cf7f13b2bd92a3b2ae252c293c863d4b5b8b05552a'
services:
  - postgresql
  - redis-server
env:
  - ENC_KEY='5aa7c2bf4ffb3cf3866b3fbea953421e12a23fabcf9410e4bff1d2fb0bdbfacb08d4d83d486be3203012d5a4be4a95c781ab32d6b4065af7020992730fbcbd42' AWS_REGION="us-east-1"
