# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e71107365f8f3b6aab8be2075c6c71484e841751031ad61eb791f69db45ab7193f41021ceee3474eda5e61e91dcf256063877a464232bb205cf5dad62a521fb
  encryption_key: a1940ca8a6dd76a20523ae579f3201079183965652a6e0f6d16d9e565a360b20ce0c61d5c549d3b9c93ee8a9d5f47186f283ea4bc72d8888ab99aebba8856cb0

test:
  secret_key_base: a64a51eab150639d40140b9d5dead71649be2ee7e97d9baae320a1336c5209ff3aa716180ea59b87405c6953db35da408110da979dc65bfb88bf67d7e50fb27b
  encrpytion_key: 5aa7c2bf4ffb3cf3866b3fbea953421e12a23fabcf9410e4bff1d2fb0bdbfacb08d4d83d486be3203012d5a4be4a95c781ab32d6b4065af7020992730fbcbd42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encryption_key: <%= ENV['ENCRYPTION_KEY'] %>
